apiVersion: apps/v1
kind: Deployment
metadata:
  name: todos
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todos
  template:
    metadata:
      labels:
        app: todos
    spec:
      containers:
        - name: todos
          image: nlcd/udagram-todos-client
          imagePullPolicy: Always
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "500m"
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: todos
spec:
  type: LoadBalancer
  selector:
    app: todos
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 80
