nguage: node_jsi
node_js:
  - 12

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"
# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  ######
  - echo "Begin to build udagram-todos-client image"
  - docker build -f client/Dockerfile -t udagram-todos-client ./client
  - docker tag udagram-todos-client nlcd/udagram-todos-client
  - echo "Finish to build udagram-api-user image"

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push nlcd/udagram-todos-client
